### ISSUE TITLE
Fix incorrect guidance for optional parameters

### ISSUE THREAD

**Issue by jdickey** [hanami/guides#35]
Consistently throughout the Guides, e.g., in the [_Usage_ section of the _Actions : Parameters_ docs](https://guides.hanamirb.org/actions/parameters/#usage), the examples for defining an `optional` param actually require it. This is due to the use of `filled` in the parameter-validation definition.

Consider this example extracted from my own code that exercises the same problem. The intent of the `optional(:profile)` rule is to define an optional param that, _if_ filled, _must_ be a string and _must_ have a maximum size of 8K:

```ruby
      class CreateParams < Hanami::Action::Params
        predicates ConversagencePredicates # defines `:email?`

        validations do
          required(:user).schema do
            required(:name).filled(:str?, size?: 3..64)
            required(:email).filled(:email?)
            optional(:profile).filled(:str?, max_size?: 8192)
          end
        end
      end
```

Attempting to validate parameters that include an empty string for `profile` produce the errors "Profile must be filled" and "Profile size cannot be greater than 8192".

Digging into the Hanami::Validations [GitHub README docs](https://github.com/hanami/validations#rules) provided the answer. When I change my `CreateParams` class to

```ruby
      class CreateParams < Hanami::Action::Params
        predicates ConversagencePredicates

        validations do
          required(:user).schema do
            required(:name).filled(:str?, size?: 3..64)
            required(:email).filled(:email?)
            optional(:profile).maybe(:str?, max_size?: 8192)
          end
        end
      end
```

the empty `profile` parameter is properly not flagged as invalid. The change, for those bleary-eyed after too many hours staring at the screen, is changing the `filled` to `maybe`. With that change, supplying `nil` is accepted (and coerced to an empty string), but supplying a non-`nil`, non-String parameter for `profile`, such as a Symbol, produces error messages and a failed validation.

As I said at the beginning, this appears to be fairly consistent mis-guidance throughout the Guides.

**Comment by kaikuchn** [comment]
Hey Jeff,

I think this is due to a conceptual misunderstanding.
The `optional` keyword only says whether the key can be omitted or not. Read this as "my input may contain the `:profile` key". Up till this point you have said nothing about the value yet.

Now when you append `filled(:str?, max_size?: 8192)` you're saying that the key may be present, and if it is, then it must be a non-blank string of max size 8192.
The `maybe` keyword allows you to have the key present and the value being `nil`. But **beware, you are no longer checking if it's filled now**. You'll need to explicitly add that check! As you can see [here](https://github.com/dry-rb/dry-validation/blob/c8b1e9f4e63262a60606780ed030902f01c30aaa/lib/dry/validation/schema/rule.rb#L90) maybe translates to `none? | filled` only if there is no other user-provided conditions. In your case `str? & max_size?(8192)` are the conditions for the right side, i.e., you get `none? | (str? & max_size?(8192))`.


That being said, I agree that the examples maybe misleading, usually when submitting something via a form, all keys are present, just their values are `nil`. In which case `optional(...).maybe(...)` or even `required(...).maybe(...)` would be better.

**Comment by jdickey** [comment]
@kaikuchn Thanks for the explainer, and sorry I'm slow catching up here.

I think your entire comment would make a dandy addition to the _Overview_ page for Validations in the Guides. Thanks also for confirming that I stumbled into exactly the validation I wanted. 😀
