### ISSUE TITLE
link_to helpers and concat

### ISSUE THREAD

**Issue by jodeci** [hanami/guides#51]
The guide indicates that `link_to` helpers do not need to be concated:

    html.div do
      link_to 'Users', routes.users_path, class: 'btn'
      hr
      link_to 'Books', routes.books_path, class: 'btn'
    end

However, in practice, only the last link renders. Upon some digging, apparently they need to be concated:

https://github.com/hanami/helpers/blob/9acd2bf17bc2e5579cdd91f8d0f88129367cb420/spec/support/fixtures.rb#L715

I'm going to assume that the code is correct and the guide needs updating?

**Comment by cllns** [comment]
It looks like this issue was brought up here: https://github.com/hanami/helpers/issues/48 and then (in the repo where the guides used to be), this text was added: https://github.com/hanami/hanami.github.io/pull/145

It looks like the text that was added was the opposite of what it should've been. It should've had the `+`s for concatenation. (Ideally we'd be able to change the helpers & view to be able to support this without concatenation IMO, but that's a different issue.)

Sorry it took so long to get back to you. Let me know if you want to open a PR for this, or I can take it if you don't want to :)
