### ISSUE TITLE
Validation example incomplete

### ISSUE THREAD

**Issue by mroderick** [hanami/guides#55]
When following the getting started guide to the letter, I am seeing the following error:

```
Failures:

  1) Add a book displays list of errors when params contains errors
     Failure/Error: expect(page).to have_content('There was a problem with your submission')
       expected to find text "There was a problem with your submission" in "Bookshelf"
     # ./spec/web/features/add_book_spec.rb:16:in `block (2 levels) in <top (required)>'

Finished in 0.12875 seconds (files took 1.55 seconds to load)
18 examples, 1 failure

Failed examples:

rspec ./spec/web/features/add_book_spec.rb:7 # Add a book displays list of errors when params contains errors
```

Adding the validation code below not only to `apps/web/templates/books/new.html.erb` but also to `apps/web/templates/books/create.html.erb` allows the tests to pass.

```erb
<% unless params.valid? %>
    <div class="errors">
        <h3>There was a problem with your submission</h3>
        <ul>
            <% params.error_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>
```

I imagine that there isn't meant to be this kind of duplication in the guide, or in 

I'd be happy to contribute a pull request, but I don't know if this is a defect of the tests or the instructions for the templates.

**Comment by cllns** [comment]
Thanks for opening this issue @mroderick! These kinds of reports are crucial to keeping the guides up-to-date.

I think you might have missed a [`template 'books/new'`](https://github.com/hanami/guides/blame/master/content/introduction/getting-started.md#L978) line in your `apps/web/views/books/create.rb` file. This tells the `Books::Create` view to use the `new.html.erb` template, instead of duplicating the file.

Feel free to close if that's the issue 🌸
If you think we should make that instruction clearer, I'd be happy to look at a PR :)
